main: 
	ifort -std08 -fpp -Qcoarray sequential_lib.F90 coarray_lib.F90 main.F90 -o "main"

times: main
	main 100
	main 200
	main 300
	main 400
	main 500
	main 600
	main 700
	main 800
	main 900
	main 1000
	main 1100
	main 1200
	main 1300
	main 1400
	main 1500
